version: "3.9"
services:
  database:
    image: 'postgres:latest'
    
    ports:
      - 5432:5432
      
    environment:
      POSTGRES_USER: postgres_username
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: Database